name: DevSecOps end to end pipeline 

on:
    workflow_dispatch:

jobs:
    code-quality:
        uses: .github/workflows/code-quality.yml@main

    secret-scan:
        uses: .github/workflows/secret-scan.yml@main
    
    dependency-scan:
        uses: .github/workflows/dependency-scan.yml@main
    
    docker-scan:
        uses: .github/workflows/docker-lint.yml@main

