name: docker build & push 

on:
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:

            - name: checkout code 
              uses: actions/checkout@v4

            - name: Login to docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ vars.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: build and push to docker hub 
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: |
                    ${{vars.DOCKER_USER}}/pipeline-app:${{github.ref_name}}
                    ${{vars.DOCKER_USER}}/pipeline-app:latest
                    ${{vars.DOCKER_USER}}/pipeline-app:${{github.sha}}