name: image scanner 

on:
    workflow_call:

jobs:
    image-scanner:
        runs-on: ubuntu-latest
        
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}
            - name: trivy Scanner
              uses: aquasecurity/trivy-action@master
              with:
                    scan-type: 'image'
                    image-ref: ${{ vars.DOCKER_USER }}/pipeline-app:latest
                    severity: 'CRITICAL,HIGH'
                    exit-code: '1'
                    ignore-unfixed: true
